name: status
on:
  workflow_run:
    workflows: test
    types: completed

jobs:
  status:
    runs-on: ubuntu-latest

    steps:
      - run: echo "${{toJSON(github.event.workflow_run)}}"

      # custom statuses?
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{github.event.workflow_run.name}}
          run_id: ${{github.event.workflow_run.id}}
          name: status
          path: status
      - name: status-test
        run: |
          ls status
          for f in status/*.json
          do
            cat $f
          done
#      - id: status
#        run: |
#          echo "::set-output name=description::$(cat statuses/x86_64.txt | tr '\n' ' ')"
#      - uses: octokit/request-action@v2.x
#        with:
#          route: POST /repos/{repo}/status/{sha}
#          repo: ${{github.repository}}
#          sha: ${{github.event.status.sha}}
#          context: ${{github.event.status.context}}
#          state: ${{github.event.status.state}}
#          description: ${{steps.status.outputs.description}}
#          target_url: ${{github.event.status.target_url}}
#    
